# Generated by Django 3.2.22 on 2023-11-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='User',
        ),
    ]
