# Generated by Django 3.2.22 on 2024-02-13 10:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sub_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='내용'),
        ),
    ]
