# Generated by Django 3.2.22 on 2024-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sub_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_blog',
            name='code_set',
            field=models.TextField(verbose_name='Code Pen'),
        ),
    ]
