# Generated by Django 3.2.22 on 2024-03-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_blog',
            name='img',
            field=models.ImageField(default=1, upload_to='Sublog_image'),
            preserve_default=False,
        ),
    ]
