# Generated by Django 3.2.22 on 2024-03-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sub_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_blog',
            name='img',
        ),
    ]
