# Generated by Django 3.2.22 on 2024-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_sub_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_blog',
            name='code_set',
            field=models.TextField(blank=True, null=True, verbose_name='Code Pen'),
        ),
    ]
