# Generated by Django 3.2.22 on 2024-03-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sub_blog_code_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_blog',
            name='code_set',
            field=models.TextField(blank=True, null=True),
        ),
    ]
